name: CI
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bs publish --buildNum=$GITHUB_RUN_NUMBER --publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
